### ISSUE TITLE
Add Vietnamese

### ISSUE THREAD

**Issue by anh-tuan** [cy33hc/vita-ezremote-client#10]
Hi, I'm adding translation for Vietnamese. Please check the attachment.

Tuan

[Vietnamese.ini.zip](https://github.com/user-attachments/files/17272043/Vietnamese.ini.zip)

**Comment by cy33hc** [comment]
@anh-tuan Vietnamese lang file add in latest version just released. Edit the /data/RMTCLI001/config.ini file and update the language settings

**Comment by anh-tuan** [comment]
Thanks, @cy33hc :) Have a nice day!
