### ISSUE TITLE
FTP working with IP but not hostname

### ISSUE THREAD

**Issue by Axce** [cy33hc/vita-ezremote-client#6]
Hello, here's my problem:

I'm trying to connect to this FTP server : `ftp.myrient.erista.me` (info here: https://myrient.erista.me/ftp/)
If I type in `ftp://ftp.myrient.erista.me`, I get an error: `426 Failed. Connection timeout`.

But the connection works perfectly if I type in the IP address : `ftp://86.107.178.161` (I get `226 Directory send OK.`)

So not a breaking issue, but I need to recheck the server's IP address whenever it changes.
Could the FTP connection support text hostnames?

Many thanks for your work!

**Comment by Axce** [comment]
(To successfully connect, I also need to input `anonymous` into username, but it's not supposed to be required by the server. I don't know if this is a client issue or if I should open another one.)

**Comment by cy33hc** [comment]
@Axce This is fixed along with some speed improvement for SMB and NFS. Please test and close. Also you don't need "anonymous" in username now. The app will automatically use the username "anonymous" if none specified.

https://github.com/cy33hc/vita-ezremote-client/releases/edit/1.03

**Comment by Axce** [comment]
Perfect, it's all good now!
Just a remark, `ftp://ftp.myrient.erista.me` works, but `ftp://ftp.myrient.erista.me/` with a final slash doesn't (426 timeout).
Thank you very much!
