### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by gilgilgan** [cy33hc/vita-ezremote-client#9]
After installation, it fails to start with an error when running. 
If you check the configuration file, the language setting field is blank and you can start it with English settings by putting English there. (My Vita is set to Korean).

If I enter Korean in the language setting, the string is displayed as “?” and does not output correctly.
As a test, I also tried setting it to Japanese, and the same thing happened.

**Comment by cy33hc** [comment]
@gilgilgan This should be fixed in latest version just released.
